services:
  quran_app:
    build:
      context: .
      dockerfile: ./Dockerfile # make sure you're in server folder
    ports:
      - "1140:1140"
    environment:
      - APP_NAME=MEEZAN_SYNC
      - QURAN_API_MYSQL_CREATE_TABLES_PATH=/app/create_tables.sql
      - FCM_ICON=https://legal.mahad.dev/documents/icon-512.png
      - REDIS_HOST=host.docker.internal
    env_file:
      - .env
